
JTA_I18N.addResourceBundle('jTweetsAnywhere', 'nl',
{
	'More': 'Meer',
	'Prev': 'Vorige',
	'Next': 'Volgende',
	'%count% new tweet': '%count% nieuwe Tweet',
	'%count% new tweets': '%count% nieuwe Tweets',
	"What's happening?": "Wat houdt je bezig?",
	'%secs% second ago': '%secs% seconde geleden',
	'%secs% seconds ago': '%secs% seconden geleden',
	'%mins% minute ago': '%mins% minuut geleden',
	'%mins% minutes ago': '%mins% minuten geleden',
	'%hours% hour ago': '%hours% uur geleden',
	'%hours% hours ago': '%hours% uur geleden',
	'%days% day ago': '%days% dag geleden',
	'%days% days ago': '%days% dagen geleden',
	'via': 'via',
	'on Twitter': 'op Twitter',
	'Reply': 'Beantwoorden',
	'Retweet': 'Retweeten',
	'Favorite': 'Toevoegen aan favorieten',
	'here': 'hier',
	'in reply to': 'als antwoord op',
	'from': 'van',
	' and %rtc% other': ' en %rtc% andere',
	' and %rtc% others': ' en %rtc% anderen',
	'Retweeted by': 'Geretweet door',
	'Sign out': 'Afmelden',
	'loading': 'laden',
	'ERROR': 'FOUT',

	'$$monthNames': [ "Jan", "Feb", "Mrt", "Apr", "Mei", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dec" ]
});
