JTA_I18N.addResourceBundle('jTweetsAnywhere', 'es',
{
	'More': 'más',
	'Prev': 'previo',
	'Next': 'siguiente',
	'%count% new tweet': '%count% nuevo tweet',
	'%count% new tweets': '%count% nuevos tweets',
	"What's happening?": "¿Qué está pasando?",
	'%secs% second ago': 'hace %secs% segundo',
	'%secs% seconds ago': 'hace %secs% segundos',
	'%mins% minute ago': 'hace %mins% minuto',
	'%mins% minutes ago': 'hace %mins% minutos',
	'%hours% hour ago': 'hace %hours% hora',
	'%hours% hours ago': 'hace %hours% horas',
	'%days% day ago': 'hace %days% día',
	'%days% days ago': 'hace %days% días',
	'via': 'vía',
	'on Twitter': 'en Twitter',
	'Reply': 'Responder',
	'Retweet': 'Retweet',
	'Favorite': 'Marcar favorito',
	'here': 'aquí',
	'in reply to': 'en respuesta a',
	'from': 'de',
	' and %rtc% other': ' y %rtc%',
	' and %rtc% others': ' y %rtc%',
	'Retweeted by': 'Retweet por',
	'Sign out': 'Salir',
	'loading': 'cargando',
	'ERROR': 'ERROR',

	'$$monthNames': [ "ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic" ]
});
