JTA_I18N.addResourceBundle('jTweetsAnywhere', 'es',
{
	'More': 'Más',
	'Prev': 'Anterior',
	'Next': 'Siguiente',
	'%count% new tweet': '%count% nuevo Tweet',
	'%count% new tweets': '%count% nuevos Tweets',
	"What's happening?": "¿Qué está pasando?",
	'%secs% second ago': 'hace %secs% segundo',
	'%secs% seconds ago': 'hace %secs% segundos',
	'%mins% minute ago': 'hace %mins% minuto',
	'%mins% minutes ago': 'hace %mins% minutos',
	'%hours% hour ago': 'hace %hours% hora',
	'%hours% hours ago': 'hace %hours% horas',
	'%days% day ago': 'hace %days% día',
	'%days% days ago': 'hace %days% días',
	'via': 'vía',
	'on Twitter': 'en Twitter',
	'Reply': 'Responder',
	'Retweet': 'Retwittear',
	'Favorite': 'Marcar favorito',
	'here': 'aquí',
	'in reply to': 'en respuesta a',
	'from': 'desde',
	' and %rtc% other': ' y %rtc%',
	' and %rtc% others': ' y %rtc%',
	'Retweeted by': 'Retwitteado por',
	'Sign out': 'Cerrar Sesión',
	'loading': 'Cargando',
	'ERROR': 'ERROR',

	'$$monthNames': [ "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic" ]
});